import { useCallback, useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowUpLeft, Building2, FileText, Loader2, Phone, Search, User, UserCheck, Users, X } from 'lucide-react';
import { api } from '../../api';

export default function PatientSearch() {
  const navigate = useNavigate();
  const [patients, setPatients] = useState([]);
  const [search, setSearch] = useState('');
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const load = useCallback(async (value = '') => { setLoading(true); setMessage(''); try { const rows = await api(`/patients?search=${encodeURIComponent(value)}`); setPatients(Array.isArray(rows) ? rows : rows?.patients || []); if (!(Array.isArray(rows) ? rows : rows?.patients || []).length) setMessage('لم يتم العثور على أي نتائج مطابقة.'); } catch (error) { setMessage(error.message || 'تعذر جلب سجلات المرضى.'); } finally { setLoading(false); } }, []);
  useEffect(() => { load(); }, [load]);
  const submit = (event) => { event.preventDefault(); load(search); };
  return <div className="min-h-screen bg-[#F8FAFC] p-3 text-slate-800 sm:p-5 md:p-8" dir="rtl"><div className="mx-auto max-w-7xl space-y-5 md:space-y-7">
    <motion.header initial={{ opacity: 0, y: -15 }} animate={{ opacity: 1, y: 0 }} className="relative overflow-hidden rounded-3xl border border-sky-100 bg-white p-5 shadow-sm md:p-8"><div className="absolute -right-16 -top-16 h-52 w-52 rounded-full bg-sky-100/80 blur-3xl"/><div className="relative flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700"><FileText size={14}/>قاعدة السجلات الطبية</span><h1 className="mt-3 text-2xl font-black text-slate-900 md:text-3xl">دليل وسجلات المرضى</h1><p className="mt-1 text-xs text-slate-500 md:text-sm">ابحث عن المريض وافتح ملفه الطبي من البطاقة مباشرة.</p></div><div className="flex items-center gap-2 rounded-2xl border border-sky-100 bg-sky-50/70 px-4 py-3 text-xs font-bold text-sky-900"><Users size={17} className="text-sky-600"/>إجمالي السجلات: {patients.length}</div></div></motion.header>
    <motion.form initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} onSubmit={submit} className="rounded-3xl border border-sky-100 bg-white p-3 shadow-sm"><div className="flex flex-col gap-3 md:flex-row"><div className="relative flex-1"><Search className="absolute right-4 top-3.5 text-sky-600" size={18}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث بالاسم، رقم الهاتف، أو الرقم القومي..." className="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50/60 pr-11 pl-10 text-sm outline-none focus:border-sky-500 focus:bg-white focus:ring-4 focus:ring-sky-100"/>{search && <button type="button" onClick={() => { setSearch(''); load(''); }} className="absolute left-3 top-2.5 rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><X size={16}/></button>}</div><button disabled={loading} className="flex h-11 items-center justify-center gap-2 rounded-2xl bg-gradient-to-l from-sky-600 to-cyan-500 px-6 text-sm font-bold text-white shadow-sm disabled:opacity-60">{loading ? <Loader2 className="animate-spin" size={17}/> : <Search size={17}/>}بحث</button></div></motion.form>
    <section className="rounded-3xl border border-sky-100 bg-white p-4 shadow-sm sm:p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-black text-slate-900">بطاقات المرضى</h2><p className="mt-1 text-xs text-slate-400">اضغط على البطاقة لعرض الملف الطبي والتاريخ العلاجي.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold text-slate-500">{patients.length} سجل</span></div>
      <AnimatePresence mode="popLayout">{patients.length ? <div className="grid gap-3 md:grid-cols-3">{patients.map((patient) => <motion.button key={patient._id} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }} whileHover={{ y: -3 }} onClick={() => navigate(`/patient-profile/${patient._id}`)} className="group rounded-3xl border border-slate-100 bg-white p-4 text-right shadow-sm transition hover:border-sky-200 hover:shadow-md hover:shadow-sky-100"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-2xl bg-sky-50 text-sky-700 transition group-hover:bg-sky-600 group-hover:text-white"><User size={21}/></div><div className="min-w-0"><h3 className="truncate text-sm font-black text-slate-900">{patient.fullName || 'بدون اسم'}</h3><p className="mt-1 text-[11px] text-slate-400">ملف طبي رقمي</p></div></div><span className="grid h-8 w-8 place-items-center rounded-xl bg-slate-50 text-sky-600 transition group-hover:bg-sky-50"><ArrowUpLeft size={16}/></span></div><div className="mt-4 grid grid-cols-2 gap-2 border-t border-slate-100 pt-3"><div className="min-w-0 rounded-xl bg-slate-50/80 p-2"><span className="flex items-center gap-1 text-[10px] text-slate-400"><Phone size={12} className="text-sky-600"/>الهاتف</span><p dir="ltr" className="mt-1 truncate text-xs font-bold text-slate-700">{patient.phone || '—'}</p></div><div className="min-w-0 rounded-xl bg-slate-50/80 p-2"><span className="flex items-center gap-1 text-[10px] text-slate-400"><Building2 size={12} className="text-sky-600"/>العيادة</span><p className="mt-1 truncate text-xs font-bold text-slate-700">{patient.clinic?.name || '—'}</p></div></div><div className="mt-3 flex items-center gap-1.5 text-[11px] text-slate-400"><UserCheck size={13} className="text-sky-600"/>أضيف بواسطة: <b className="truncate text-slate-600">{patient.createdBy?.name || 'سجل قديم'}</b></div></motion.button>)}</div> : <div className="grid min-h-64 place-items-center text-center"><div><Users className="mx-auto text-slate-300" size={34}/><p className="mt-3 text-sm text-slate-400">{loading ? 'جارٍ البحث في السجلات...' : message || 'لا توجد بيانات متاحة.'}</p></div></div>}</AnimatePresence>
    </section>
  </div></div>;
}
