import { useContext, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { CalendarDays, ChevronLeft, Clock3, Plus, UsersRound } from 'lucide-react';
import { AuthContext } from '../../AuthProvider';
import { api } from '../../api';

export default function Home() {
  const { admin } = useContext(AuthContext);
  const [appointments, setAppointments] = useState([]);
  const [patientCount, setPatientCount] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => { (async () => { try {
    const [nextAppointments, patients] = await Promise.all([api('/appointments', { showLoading: false }), api('/patients', { showLoading: false })]);
    setAppointments(nextAppointments); setPatientCount(patients.length);
  } finally { setLoading(false); } })(); }, []);

  return <section className="min-h-[calc(100vh-5rem)] bg-[#f5f9fc] p-4 md:p-8" dir="rtl"><div className="mx-auto max-w-7xl space-y-6">
    <header className="relative overflow-hidden rounded-[2rem] bg-slate-950 p-7 text-white shadow-xl md:p-10"><div className="absolute -left-20 -top-24 h-80 w-80 rounded-full bg-cyan-500/25 blur-3xl"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><span className="rounded-full border border-cyan-300/30 bg-cyan-400/10 px-3 py-1 text-xs font-bold text-cyan-200">DOCPOINT · لوحة التشغيل</span><h1 className="mt-5 text-3xl font-black md:text-4xl">أهلاً {admin?.name || admin?.username}</h1><p className="mt-3 max-w-xl text-sm leading-7 text-slate-300">نظرة سريعة على نشاط العيادة، المرضى والحجوزات القادمة خلال الأسبوع.</p></div><Link to="/appointments" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-cyan-400 px-5 py-3 text-sm font-black text-slate-950"><CalendarDays size={18}/>إدارة الحجوزات<ChevronLeft size={17}/></Link></div></header>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><article className="rounded-3xl border border-sky-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-500">مرضى مسجلون</p><b className="mt-2 block text-3xl text-slate-900">{patientCount}</b></div><div className="rounded-2xl bg-sky-50 p-3 text-sky-700"><UsersRound size={24}/></div></div><Link to="/search" className="mt-5 flex items-center gap-1 text-xs font-bold text-sky-700">عرض سجل المرضى <ChevronLeft size={14}/></Link></article><article className="rounded-3xl border border-cyan-100 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-xs font-bold text-slate-500">حجوزات الأسبوع القادم</p><b className="mt-2 block text-3xl text-slate-900">{appointments.length}</b></div><div className="rounded-2xl bg-cyan-50 p-3 text-cyan-700"><CalendarDays size={24}/></div></div><Link to="/appointments" className="mt-5 flex items-center gap-1 text-xs font-bold text-cyan-700">فتح قائمة الحجوزات <ChevronLeft size={14}/></Link></article><Link to="/register" className="group rounded-3xl bg-gradient-to-br from-sky-600 to-cyan-500 p-5 text-white shadow-md"><Plus size={25}/><b className="mt-7 block text-lg">إضافة مريض جديد</b><span className="mt-1 block text-xs text-sky-100">إنشاء ملف طبي وربطه بالعيادة</span><span className="mt-5 flex items-center gap-1 text-xs font-bold">فتح التسجيل <ChevronLeft size={14}/></span></Link></div>
    <section className="overflow-hidden rounded-3xl border border-sky-100 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-black text-slate-900">المواعيد القادمة</h2><p className="mt-1 text-xs text-slate-500">كل الحجوزات المحفوظة خلال الأيام السبعة القادمة</p></div><Clock3 className="text-sky-600" size={22}/></div><div className="divide-y divide-slate-100">{loading ? <p className="p-8 text-center text-sm text-slate-400">جارٍ تحميل بيانات الأسبوع...</p> : appointments.length ? appointments.slice(0, 6).map((item) => <div key={item._id} className="flex items-center gap-3 p-4"><div className="grid h-10 w-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><CalendarDays size={18}/></div><div className="flex-1"><b className="text-sm text-slate-900">{item.patient?.fullName || 'مريض محذوف'}</b><p className="mt-1 text-xs text-slate-500"><b className="text-sky-700">{new Date(item.appointmentAt).toLocaleDateString('ar-EG', { weekday: 'long' })}</b> · {item.patient?.phone} · {new Date(item.appointmentAt).toLocaleString('ar-EG', { dateStyle: 'medium', timeStyle: 'short' })}</p></div></div>) : <div className="p-10 text-center"><CalendarDays className="mx-auto text-slate-300" size={30}/><p className="mt-3 text-sm text-slate-400">لا توجد حجوزات خلال الأسبوع القادم.</p><Link to="/appointments" className="mt-3 inline-block text-xs font-bold text-sky-700">أنشئ أول حجز</Link></div>}</div></section>
  </div></section>;
}
